name: my_calls_app
description: A new Flutter project for My Calls.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted for current Flutter/Dart SDK typical ranges

dependencies:
  flutter:
    sdk: flutter

  flutter_webrtc: ^0.9.47 # Check for the latest compatible version
  web_socket_channel: ^2.4.0 # For WebSocket communication
  provider: ^6.0.5 # For state management, optional but good practice
  http: ^1.1.0 # Explicitly add/ensure http is present
  intl: ^0.18.1 # Explicitly add/ensure intl is present (used by ConversationsScreen)
  
  # E2EE Libraries
  libsignal_protocol_dart: ^0.2.1 # Using this as the chosen Signal library. Actual version may vary.
  flutter_secure_storage: ^9.0.0 
  shared_preferences: ^2.2.2 # Using a slightly more recent common version
  convert: ^3.1.1 
  
  # Other utilities that might be helpful for Signal or general use
  path_provider: ^2.1.1 # Using a slightly more recent common version
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Or a more recent version

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
